### ISSUE TITLE
APK gone?

### ISSUE THREAD

**Issue by IzzySoft** [mileskrell/text-torch#1]
Is there any reason you removed the APK file from `releases/`? Could you please put it back? Thanks!

**Comment by mileskrell** [comment]
I didn't realize that an APK was needed for anything (assuming I could just direct users to download the app from F-Droid once it was available there). I've just added one again.

**Comment by IzzySoft** [comment]
Thanks! And apologies for the missing context: It's not needed for F-Droid itself once your app is listed there – but for [keeping it in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.mileskrell.texttorch) until then. Of course I could simply disable update check; but as the inclusion process sometimes takes months, you might have updates before that. My updater checks once a day.

Once your app is on F-Droid, I can either keep it in mine for those who installed it from there (else they'd need to uninstall and reinstall, as signatures don't match) and for faster updates – or remove it after a week's overlap, which ever you prefer. For orientation: in most cases it's then removed from mine, but I have no problems keeping it as long as the authors provide the APKs. Choice I leave with you, just let me know in time.

**Comment by mileskrell** [comment]
I'm fine with the app being removed from your repo once it's available on F-Droid. Thanks!

**Comment by IzzySoft** [comment]
Thanks! I'll make a corresponding note in my metadata here then.
